### ISSUE TITLE
R6S insta-crashes upon splash screen load

### ISSUE THREAD

**Issue by arrrbeee** [haram/splendid_implanter#3]
Title.

Steps to reproduce:
1) Launch `cmd.exe` as sysadmin
2) Initiate command `splendid_implater.exe yourfile.dll R6Game`
3) Game loads, console shows .dll inject and exits.
4) Game crashes when it gets to splash screen (e.g. 'Press Any Button')

**Comment by haram** [comment]
Fixed.
