### ISSUE TITLE
Injector stops at waiting for BE Serivce

### ISSUE THREAD

**Issue by xliquid808** [haram/splendid_implanter#8]
The injector won't inject it just stops at waiting for BEService I ran it when I was in the lobby and I ran it in administrator mode I also tried it when before I ran anything and I have the example code in my maindll.cpp

**Comment by carsonsobolewski** [comment]
you're supposed to run it before you open r6 siege

**Comment by xliquid808** [comment]
nvm. battlEye was fucking with me It just didn't run for some reason
